#!/usr/bin/env bash
set -euo pipefail

OPENCODE_AGENT="${OPENCODE_AGENT:-steward}"
OPENCODE_MODEL="${OPENCODE_MODEL:-}"
REPORT_PATH="${REPORT_PATH:-.opencode/reports/opencode-review.md}"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${REPO_ROOT}" ]]; then
  echo "ERROR: Not a git repo. Run from inside a git repository." >&2
  exit 2
fi
cd "${REPO_ROOT}"

mkdir -p "$(dirname "${REPORT_PATH}")"

TMPDIR="$(mktemp -d)"
PATCH_FILE="${TMPDIR}/changes.patch"

HAS_HEAD=0
if git rev-parse --verify HEAD >/dev/null 2>&1; then
  HAS_HEAD=1
fi

{
  echo "# Patch generated by scripts/opencode-review.sh"
  echo

  if [[ "${HAS_HEAD}" -eq 1 ]]; then
    echo "# Diff vs HEAD (staged + unstaged)"
    echo
    git diff --patch --minimal --no-color HEAD || true
  else
    echo "# No HEAD commit detected (new repo). Including staged + unstaged diffs."
    echo
    echo "## Unstaged diff"
    git diff --patch --minimal --no-color || true
    echo
    echo "## Staged diff"
    git diff --patch --minimal --no-color --cached || true
  fi

  echo
  echo "# Untracked files"
  echo
  UNTRACKED_FILES="$(git ls-files --others --exclude-standard || true)"

  if [[ -z "${UNTRACKED_FILES}" ]]; then
    echo "(none)"
  else
    while IFS= read -r f; do
      [[ -z "${f}" ]] && continue
      echo
      echo "## ${f}"
      git diff --no-index --no-color -- /dev/null "${f}" || true
    done <<< "${UNTRACKED_FILES}"
  fi
} > "${PATCH_FILE}"

# If nothing changed, avoid burning tokens.
if ! grep -qE '^(\+|\-|diff --git|@@)' "${PATCH_FILE}"; then
  cat > "${REPORT_PATH}" <<EOF
RESULT: PASS
SUMMARY
- OpenCode review skipped: no diff detected.

MUST FIX
- (none)

SHOULD FIX
- (none)
EOF
  echo "Wrote: ${REPORT_PATH}"
  exit 0
fi

PROMPT=$(cat <<'EOF'
Run the Code Steward review on the attached patch.

Rules:
- Use your required output format.
- Be strict about MUST FIX vs SHOULD FIX.
EOF
)

RUN_ARGS=(run --agent "${OPENCODE_AGENT}" "${PROMPT}" --file "${PATCH_FILE}")
if [[ -n "${OPENCODE_MODEL}" ]]; then
  RUN_ARGS+=(--model "${OPENCODE_MODEL}")
fi

opencode "${RUN_ARGS[@]}" > "${REPORT_PATH}"

echo "Wrote: ${REPORT_PATH}"

if grep -q '^RESULT: FAIL' "${REPORT_PATH}"; then
  echo "OpenCode review: FAIL (see ${REPORT_PATH})" >&2
  exit 1
fi

echo "OpenCode review: PASS"
